name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Actualiza la fecha en el README
      - name: Update Date
        uses: josStorer/github-profile-summary-cards@release

      # Actualiza la actividad reciente
      - name: Update Recent Activity
        uses: Readme-Workflows/recent-activity@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Actualiza los últimos repositorios
      - name: Update Repositories
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README"
